import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { GithubIcon } from "lucide-react";
import { ThemeToggle } from "@/components/theme/theme-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="min-h-screen flex flex-col">
            {children}
            <footer className="mt-auto mx-auto w-full max-w-5xl px-4 py-8">
              <GithubIcon />
              {/* {!!slateConfig.socialLinks && <SocialLinks client:visible />} */}
              <div className="mt-4 flex items-center justify-between">
                <div className="text-slate-600 dark:text-slate-400 text-sm">
                  {"copyright"}
                </div>
                {/* S theme selection */}
                <ThemeToggle />
                {/* E theme selection */}
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
